[project]
name = "TikTakToe"
version = "0.1.0"
description = "TikTakToe game ;3"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.0",
    "playsound>=1.3.0",
    "python-dotenv>=1.0.1",
    "pywebview>=5.4",
]
